<?php
 goto ym0Bz; o23Tv: $profiles = $con->query("\x53\105\114\x45\x43\x54\x20\52\x20\106\122\x4f\x4d\40\x70\x72\x6f\146\151\154\x65\x73\40\x4f\x52\x44\105\x52\40\102\131\x20\154\141\x73\164\163\x65\x61\x72\143\150\x20\x44\105\x53\103\40\114\111\x4d\111\x54\x20\66"); goto jsgNi; zynKK: if (!empty($recentreports_array)) { foreach ($recentreports_array as $report) { ?>
<form action="reports"method="post"><input name="type"type="hidden"value="show"> <input name="reportid"type="hidden"value="<?php  echo $report["\151\x64"]; ?>
"> <button class="btn btn-panel panel-item"type="submit"style="text-align:left!important"><h5 class="panel-title">#<?php  echo $report["\151\144"]; echo $report["\164\151\164\x6c\x65"]; ?>
</h5><p class="panel-author">door:<?php  echo $report["\x61\x75\164\x68\x6f\162"]; ?>
</p></button></form><?php  } } else { ?>
<p>Geen personen opgezocht..</p><?php  } goto S3w8d; pTA74: if (!$_SESSION["\x6c\157\x67\x67\145\144\151\156"]) { Header("\x4c\x6f\143\x61\164\151\x6f\x6e\72\x20\154\157\x67\151\x6e"); } goto o23Tv; piJmf: if ($_SESSION["\162\157\154\x65"] == "\141\x64\155\x69\156") { ?>
<input name="imgbtn"type="image"alt="Tool Tip"onclick='location.href="users"'src="assets/images/adminbutton.png"><?php  } goto yW9Na; Rglt2: if ($_SESSION["\162\157\154\145"] == "\141\x64\x6d\151\x6e") { ?>
<li class="nav-item dropdown"><a class="nav-link dropdown-toggle"href="#"aria-expanded="false"aria-haspopup="true"data-toggle="dropdown"id="navbarDropdown"role="button">ADMIN</a><div class="dropdown-menu"aria-labelledby="navbarDropdown"><a class="dropdown-item"href="laws">STRAFFEN</a> <a class="dropdown-item"href="users">GEBRUIKERS</a></div></li><?php  } goto de9b_; Scf8O: $reports = $con->query("\x53\105\114\105\103\124\x20\x2a\40\106\122\x4f\115\40\162\x65\160\x6f\162\164\x73\40\x4f\122\x44\105\x52\x20\x42\131\40\143\162\145\141\164\x65\x64\40\x44\x45\123\103\x20\x4c\111\x4d\111\124\40\66"); goto Gyeg9; WMwi6: ?>
.</span></a></li><li class="nav-item"><a class="nav-button"href="logout"><button class="btn btn-logout btn-outline-light my-2 my-sm-0"type="button">LOG UIT</button></a></li></ul><ul class="navbar-nav ml-auto"><li class="nav-item active"><a class="nav-link"href="dashboard">DASHBOARD</a></li><li class="nav-item dropdown"><a class="nav-link dropdown-toggle"href="#"aria-expanded="false"aria-haspopup="true"data-toggle="dropdown"id="navbarDropdown"role="button">OPZOEKEN</a><div class="dropdown-menu"aria-labelledby="navbarDropdown"><a class="dropdown-item"href="profiles">PERSONEN</a> <a class="dropdown-item"href="reports">RAPPORT</a></div></li><li class="nav-item"><a class="nav-link"href="warrants">ARRESTATIEBEVELEN</a></li><?php  goto Rglt2; yW9Na: ?>
</div><div class="dashboard-container"><div class="left-panel-container"><h5 class="panel-container-title">Laatste rapportages</h5><?php  goto zynKK; Gyeg9: $recentreports_array = array(); goto NDhKk; MsYL3: $lastname = substr($_SESSION["\156\x61\155\145"], $last_word_start); goto q0mzg; NDhKk: while ($data = $reports->fetch_assoc()) { $recentreports_array[] = $data; } goto ZH1Ac; ry5I9: while ($data = $profiles->fetch_assoc()) { $recentsearch_array[] = $data; } goto Scf8O; jsgNi: $recentsearch_array = array(); goto ry5I9; ym0Bz: require "\162\x65\161\x75\151\x72\145\163\57\143\x6f\x6e\146\151\147\56\160\x68\x70"; goto pTA74; yMtSh: if (!empty($recentsearch_array)) { foreach ($recentsearch_array as $person) { ?>
<form action="profiles"method="post"><input name="type"type="hidden"value="show"> <input name="personid"type="hidden"value="<?php  echo $person["\151\144"]; ?>
"> <button class="btn btn-panel panel-item"type="submit"style="text-align:left!important"><h5 class="panel-title"><?php  echo $person["\x66\165\x6c\154\156\141\155\145"]; ?>
</h5><p class="panel-author">BSN:<?php  echo $person["\x63\151\164\151\x7a\x65\x6e\151\144"]; ?>
</p></button></form><?php  } } else { ?>
<p>Geen personen opgezocht..</p><?php  } goto Jb5hQ; J0B5j: echo $_SESSION["\162\141\x6e\x6b"] . "\40" . $firstname . "\40" . substr($lastname, 0, 1); goto WMwi6; ZH1Ac: $name = explode("\x20", $_SESSION["\x6e\141\x6d\145"]); goto JRadb; ZK9xk: $last_word_start = strrpos($_SESSION["\x6e\141\x6d\x65"], "\40") + 1; goto MsYL3; de9b_: ?>
<li class="nav-item"><a class="nav-link-report"href="createreport">NIEUW RAPPORT</a></li></ul></div></nav><main class="container"role="main"><div class="content-introduction"><h3>INTRANET DASHBOARD</h3><p class="lead">V1.0</p><input name="imgbtn"type="image"alt="Tool Tip"onclick='location.href="profiles"'src="assets/images/unknown.png"> <input name="imgbtn"type="image"alt="Tool Tip"onclick='location.href="sssss"'src="assets/images/aangiftebutton.png"> <input name="imgbtn"type="image"alt="Tool Tip"onclick='location.href="soon"'src="assets/images/beveiligingbutton.png"><?php  goto piJmf; S3w8d: ?>
</div><div class="right-panel-container"><h5 class="panel-container-title">Laatst opgezocht</h5><div class="panel-list"><?php  goto yMtSh; q0mzg: ?>
<!doctypehtml><html lang="en"><head><meta charset="utf-8"><meta content="width=device-width,initial-scale=1,shrink-to-fit=no"name="viewport"><meta content=""name="description"><meta content=""name="author"><link href="https://www.politie.nl/politie2018/assets/images/icons/favicon.ico"rel="shortcut icon"type="image/x-icon"><link href="https://www.politie.nl/politie2018/assets/images/icons/favicon-16.png"rel="icon"type="image/png"sizes="16x16"><link href="https://www.politie.nl/politie2018/assets/images/icons/favicon-32.png"rel="icon"type="image/png"sizes="32x32"><link href="https://www.politie.nl/politie2018/assets/images/icons/favicon-64.png"rel="icon"type="image/png"sizes="64x64"><title>Politie Databank</title><link href="https://getbootstrap.com/docs/4.0/examples/starter-template/"rel="canonical"><link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"rel="stylesheet"crossorigin="anonymous"integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"><link href="assets/css/main.css"rel="stylesheet"></head><body oncontextmenu="return!1"><nav class="bg-custom fixed-top navbar navbar-custom navbar-expand-lg"><div class="collapse navbar-collapse"id="navbarsExampleDefault"><ul class="navbar-nav mr-auto"><li class="nav-item"><a class="nav-label"href="#"><img alt=""height="22"src="assets/images/icon.png"width="22"> <span class="title">Welkom<?php  goto J0B5j; JRadb: $firstname = $name[0]; goto ZK9xk; Jb5hQ: ?>
</div></div></div></main><script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"crossorigin="anonymous"integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"crossorigin="anonymous"integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"></script><script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"crossorigin="anonymous"integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"></script><script src="assets/js/main.js"></script></body></html>